Don't set `ActiveStorage::Current.host`
This causes test runs on CI to fail with:

   Failure/Error: ActiveStorage::Current.host = 'https://www.example.com'

     NoMethodError:
       undefined method `host=' for #<ActiveStorage::Current:0x00007f12e8d2bbb0 @attributes={}>
     # ./spec/spec_helper.rb:28:in `block (2 levels) in <top (required)>'