Don't require `selenium-webdriver`
Currently the Gemfile requires `webdrivers` which is all we need for the
current version of the CircleCI orbs.

There's an error we're hoping to resolve by updating this version:
When `selenium-webdriver` and `webdrivers` are included we end up with
this error:

    NoMethodError:
      undefined method `bitsize' for Selenium::WebDriver::Platform:Module